### ISSUE TITLE
LibItemUpgradeInfo-1.0

### ISSUE THREAD

**Issue by Rav99** [liquidbase/DuffedUIv8-Legion-Alpha#7]
Error on new chars after login:
Message: ...ce\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:144: attempt to perform arithmetic on local 'numBonuses' (a string value)
Time: 06/27/16 16:14:11
Count: 1
Stack: ...ce\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:144: in function `GetUpgradeID'
...ce\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:263: in function `GetUpgradedItemLevel'
Interface\AddOns\DuffedUI\modules\plugins\ilvlr.lua:59: in function <Interface\AddOns\DuffedUI\modules\plugins\ilvlr.lua:45>
Interface\AddOns\DuffedUI\modules\plugins\ilvlr.lua:110: in function <Interface\AddOns\DuffedUI\modules\plugins\ilvlr.lua:107>

Locals: self = <table> {
 IsBoe = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:294
 GetUpgradeID = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:137
 GetItemLevelUpgrade = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:187
 GetUpgradedItemLevel = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:256
 _CheckUpgradeTable = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:478
 GetCacheStats = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:405
 GetItemUpgradeInfo = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:209
 GetItemID = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:381
 GetCurrentUpgrade = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:158
 GetMaximumUpgrade = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:172
 itemcache = <table> {
 }
 IsBoa = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:308
 GetHeirloomTrueLevel = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:234
 IsBop = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:280
 IsHeirloom = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:333
 GetCachingGetItemInfo = <function> defined @Interface\AddOns\DuffedUI\libs\LibItemUpgradeInfo-1.0\Core.lua:402
}
itemString = "[]"
itemString = "item:124236::::::::100:251:4:3::529:::"
instaid = 4
_ = "3"
numBonuses = ""
affixes = "529:::"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = 4
(*temporary) = ""
(*temporary) = ""
(*temporary) = ""
(*temporary) = "attempt to perform arithmetic on local 'numBonuses' (a string value)"
select = <function> defined =[C]:-1
strsplit = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1

**Comment by liquidbase** [comment]
Tested the issue with various items, classes and specs. At the current version 8.35.019 there is no issue like that.

**Comment by Rav99** [comment]
After a WTF wipe the error is gone +1:

**Comment by Rav99** [comment]
mhhh the error came back with new chars and i think i have a fixed for the first login.
i think GetUpgradeItemLevel can be nil so i put it in ilvlr and it fix the error.

59: local itemlevel = LibItemUpgrade:GetUpgradedItemLevel(item) or 0 or nil
